server.servlet.session.cookie.secure=true
apecan.ativacao.entrega=email
apecan.redefinicao.entrega=email
apecan.url-publica=${APECAN_PUBLIC_URL}
spring.datasource.url=${APECAN_DB_URL}
spring.datasource.username=${APECAN_DB_USERNAME}
spring.datasource.password=${APECAN_DB_PASSWORD}
spring.mail.host=${APECAN_MAIL_HOST:localhost}
spring.mail.username=${APECAN_MAIL_USERNAME:}
spring.mail.password=${APECAN_MAIL_PASSWORD:}
