CREATE TABLE auditoria_exclusoes_teste (
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_responsavel_usuario BIGINT NOT NULL,
    tipo_registro VARCHAR(30) NOT NULL,
    id_registro BIGINT NOT NULL,
    justificativa VARCHAR(500) NOT NULL,
    quantidade_removida INTEGER NOT NULL,
    ocorrido_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auditoria_exclusoes_teste PRIMARY KEY (id_evento),
    CONSTRAINT fk_auditoria_exclusoes_responsavel FOREIGN KEY (id_responsavel_usuario)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_auditoria_exclusoes_tipo CHECK (
        tipo_registro IN ('PACIENTE', 'VOLUNTARIO', 'EQUIPAMENTO', 'CATEGORIA', 'EMPRESTIMO',
                          'DOACAO', 'DESPESA', 'MOVIMENTACAO')
    ),
    CONSTRAINT ck_auditoria_exclusoes_quantidade CHECK (quantidade_removida > 0)
);

CREATE INDEX ix_auditoria_exclusoes_responsavel_data
    ON auditoria_exclusoes_teste (id_responsavel_usuario, ocorrido_em DESC);
