CREATE TABLE usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(150) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    login VARCHAR(50) NOT NULL,
    cpf CHAR(11) NOT NULL,
    email VARCHAR(254) NOT NULL,
    foto_url VARCHAR(500) NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    tipo_de_perfil VARCHAR(20) NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'ATIVO',
    primeiro_acesso_pendente BOOLEAN NOT NULL DEFAULT TRUE,
    senha_definitiva_em TIMESTAMP,
    criado_por_usuario_id BIGINT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP,
    desativado_em TIMESTAMP,
    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuarios_login UNIQUE (login),
    CONSTRAINT uq_usuarios_cpf UNIQUE (cpf),
    CONSTRAINT uq_usuarios_email UNIQUE (email),
    CONSTRAINT fk_usuarios_criado_por FOREIGN KEY (criado_por_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_usuarios_cpf CHECK (cpf ~ '^[0-9]{11}$'),
    CONSTRAINT ck_usuarios_telefone CHECK (telefone ~ '^[0-9]{10,15}$'),
    CONSTRAINT ck_usuarios_tipo_de_perfil CHECK (
        tipo_de_perfil IN ('ADMINISTRADOR', 'USUARIO')
    ),
    CONSTRAINT ck_usuarios_status CHECK (status IN ('ATIVO', 'INATIVO')),
    CONSTRAINT ck_usuarios_desativacao CHECK (
        (status = 'ATIVO' AND desativado_em IS NULL)
        OR status = 'INATIVO'
    )
);

CREATE TABLE tokens_redefinicao_senha (
    id_token BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    solicitado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expira_em TIMESTAMP NOT NULL,
    utilizado_em TIMESTAMP,
    CONSTRAINT pk_tokens_redefinicao_senha PRIMARY KEY (id_token),
    CONSTRAINT uq_tokens_redefinicao_senha_hash UNIQUE (token_hash),
    CONSTRAINT fk_tokens_redefinicao_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_tokens_redefinicao_hash CHECK (token_hash ~ '^[0-9A-Fa-f]{64}$'),
    CONSTRAINT ck_tokens_redefinicao_expiracao CHECK (expira_em > solicitado_em),
    CONSTRAINT ck_tokens_redefinicao_utilizacao CHECK (
        utilizado_em IS NULL OR utilizado_em >= solicitado_em
    )
);

CREATE TABLE pacientes (
    id_paciente BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(150) NOT NULL,
    cpf CHAR(11) NOT NULL,
    data_nascimento DATE NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    local_tratamento VARCHAR(150) NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'ATIVO',
    criado_por_usuario_id BIGINT NOT NULL,
    atualizado_por_usuario_id BIGINT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP,
    desativado_em TIMESTAMP,
    CONSTRAINT pk_pacientes PRIMARY KEY (id_paciente),
    CONSTRAINT uq_pacientes_cpf UNIQUE (cpf),
    CONSTRAINT fk_pacientes_criado_por FOREIGN KEY (criado_por_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_pacientes_atualizado_por FOREIGN KEY (atualizado_por_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_pacientes_cpf CHECK (cpf ~ '^[0-9]{11}$'),
    CONSTRAINT ck_pacientes_telefone CHECK (telefone ~ '^[0-9]{10,15}$'),
    CONSTRAINT ck_pacientes_nascimento CHECK (data_nascimento <= CURRENT_DATE),
    CONSTRAINT ck_pacientes_status CHECK (status IN ('ATIVO', 'INATIVO', 'FALECIDO')),
    CONSTRAINT ck_pacientes_desativacao CHECK (
        (status = 'ATIVO' AND desativado_em IS NULL)
        OR status IN ('INATIVO', 'FALECIDO')
    )
);

CREATE TABLE historico_status_paciente (
    id_historico BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_paciente BIGINT NOT NULL,
    status VARCHAR(10) NOT NULL,
    alterado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    alterado_por_usuario_id BIGINT NOT NULL,
    observacao VARCHAR(255),
    CONSTRAINT pk_historico_status_paciente PRIMARY KEY (id_historico),
    CONSTRAINT fk_historico_status_paciente FOREIGN KEY (id_paciente)
        REFERENCES pacientes (id_paciente),
    CONSTRAINT fk_historico_status_usuario FOREIGN KEY (alterado_por_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_historico_status CHECK (status IN ('ATIVO', 'INATIVO', 'FALECIDO'))
);

CREATE TABLE voluntarios (
    id_voluntario BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(150) NOT NULL,
    cpf CHAR(11) NOT NULL,
    data_nascimento DATE NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'ATIVO',
    criado_por_usuario_id BIGINT NOT NULL,
    atualizado_por_usuario_id BIGINT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP,
    desativado_em TIMESTAMP,
    CONSTRAINT pk_voluntarios PRIMARY KEY (id_voluntario),
    CONSTRAINT uq_voluntarios_cpf UNIQUE (cpf),
    CONSTRAINT fk_voluntarios_criado_por FOREIGN KEY (criado_por_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_voluntarios_atualizado_por FOREIGN KEY (atualizado_por_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_voluntarios_cpf CHECK (cpf ~ '^[0-9]{11}$'),
    CONSTRAINT ck_voluntarios_telefone CHECK (telefone ~ '^[0-9]{10,15}$'),
    CONSTRAINT ck_voluntarios_nascimento CHECK (data_nascimento <= CURRENT_DATE),
    CONSTRAINT ck_voluntarios_status CHECK (status IN ('ATIVO', 'INATIVO')),
    CONSTRAINT ck_voluntarios_desativacao CHECK (
        (status = 'ATIVO' AND desativado_em IS NULL)
        OR status = 'INATIVO'
    )
);

CREATE TABLE categorias_equipamentos (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(80) NOT NULL,
    descricao VARCHAR(255),
    criado_por_usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP,
    CONSTRAINT pk_categorias_equipamentos PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categorias_equipamentos_nome UNIQUE (nome),
    CONSTRAINT fk_categorias_equipamentos_criado_por FOREIGN KEY (criado_por_usuario_id)
        REFERENCES usuarios (id_usuario)
);

CREATE TABLE equipamentos (
    id_equipamento BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_categoria BIGINT NOT NULL,
    id_doacao BIGINT,
    estado_conservacao VARCHAR(15) NOT NULL,
    status VARCHAR(15) NOT NULL DEFAULT 'ATIVO',
    criado_por_usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP,
    CONSTRAINT pk_equipamentos PRIMARY KEY (id_equipamento),
    CONSTRAINT fk_equipamentos_categoria FOREIGN KEY (id_categoria)
        REFERENCES categorias_equipamentos (id_categoria),
    CONSTRAINT fk_equipamentos_criado_por FOREIGN KEY (criado_por_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_equipamentos_estado_conservacao CHECK (
        estado_conservacao IN ('NOVO', 'BOM', 'REGULAR', 'DANIFICADO')
    ),
    CONSTRAINT ck_equipamentos_status CHECK (
        status IN ('ATIVO', 'INATIVO', 'EMPRESTADO')
    )
);

CREATE TABLE emprestimos_equipamentos (
    id_emprestimo BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_equipamento BIGINT NOT NULL,
    id_paciente BIGINT NOT NULL,
    data_emprestimo DATE NOT NULL,
    data_devolucao DATE,
    registrado_por_usuario_id BIGINT NOT NULL,
    observacao VARCHAR(255),
    CONSTRAINT pk_emprestimos_equipamentos PRIMARY KEY (id_emprestimo),
    CONSTRAINT fk_emprestimos_equipamento FOREIGN KEY (id_equipamento)
        REFERENCES equipamentos (id_equipamento),
    CONSTRAINT fk_emprestimos_paciente FOREIGN KEY (id_paciente)
        REFERENCES pacientes (id_paciente),
    CONSTRAINT fk_emprestimos_registrado_por FOREIGN KEY (registrado_por_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_emprestimos_datas CHECK (
        data_devolucao IS NULL OR data_devolucao >= data_emprestimo
    )
);

CREATE TABLE doacoes (
    id_doacao BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_doacao VARCHAR(30) NOT NULL,
    quantidade DECIMAL(12,3),
    unidade VARCHAR(30),
    data_doacao DATE NOT NULL,
    fonte_doacao VARCHAR(150) NOT NULL,
    registrado_por_usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_doacoes PRIMARY KEY (id_doacao),
    CONSTRAINT fk_doacoes_registrado_por FOREIGN KEY (registrado_por_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_doacoes_tipo CHECK (
        tipo_doacao IN ('MONETARIA', 'EQUIPAMENTO', 'OUTRO_BEM')
    ),
    CONSTRAINT ck_doacoes_quantidade CHECK (quantidade IS NULL OR quantidade > 0),
    CONSTRAINT ck_doacoes_conteudo CHECK (
        (tipo_doacao IN ('MONETARIA', 'EQUIPAMENTO') AND quantidade IS NULL AND unidade IS NULL)
        OR (tipo_doacao = 'OUTRO_BEM' AND quantidade IS NOT NULL AND unidade IS NOT NULL)
    )
);

ALTER TABLE equipamentos
    ADD CONSTRAINT fk_equipamentos_doacao FOREIGN KEY (id_doacao)
        REFERENCES doacoes (id_doacao);

CREATE TABLE doacao_voluntarios (
    id_doacao BIGINT NOT NULL,
    id_voluntario BIGINT NOT NULL,
    papel VARCHAR(20) NOT NULL,
    CONSTRAINT pk_doacao_voluntarios PRIMARY KEY (id_doacao, id_voluntario, papel),
    CONSTRAINT fk_doacao_voluntarios_doacao FOREIGN KEY (id_doacao)
        REFERENCES doacoes (id_doacao),
    CONSTRAINT fk_doacao_voluntarios_voluntario FOREIGN KEY (id_voluntario)
        REFERENCES voluntarios (id_voluntario),
    CONSTRAINT ck_doacao_voluntarios_papel CHECK (papel IN ('DOADOR', 'RESPONSAVEL'))
);

CREATE TABLE movimentacoes_financeiras (
    id_movimentacao BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_movimentacao VARCHAR(10) NOT NULL,
    valor DECIMAL(12,2) NOT NULL,
    data_movimentacao DATE NOT NULL,
    destino VARCHAR(150) NOT NULL,
    origem_tipo VARCHAR(20) NOT NULL,
    origem_descricao VARCHAR(150) NOT NULL,
    id_doacao BIGINT,
    registrado_por_usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_movimentacoes_financeiras PRIMARY KEY (id_movimentacao),
    CONSTRAINT uq_movimentacoes_doacao UNIQUE (id_doacao),
    CONSTRAINT fk_movimentacoes_doacao FOREIGN KEY (id_doacao)
        REFERENCES doacoes (id_doacao),
    CONSTRAINT fk_movimentacoes_registrado_por FOREIGN KEY (registrado_por_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_movimentacoes_tipo CHECK (tipo_movimentacao IN ('ENTRADA', 'SAIDA')),
    CONSTRAINT ck_movimentacoes_valor CHECK (valor > 0),
    CONSTRAINT ck_movimentacoes_origem CHECK (origem_tipo IN ('DOACAO', 'OUTRO_MEIO')),
    CONSTRAINT ck_movimentacoes_doacao CHECK (
        (origem_tipo = 'DOACAO' AND id_doacao IS NOT NULL AND tipo_movimentacao = 'ENTRADA')
        OR (origem_tipo = 'OUTRO_MEIO' AND id_doacao IS NULL)
    )
);

CREATE TABLE despesas (
    id_despesa BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_despesa VARCHAR(50) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    numero_nota_fiscal VARCHAR(20) NOT NULL,
    id_movimentacao_financeira BIGINT NOT NULL,
    registrado_por_usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_despesas PRIMARY KEY (id_despesa),
    CONSTRAINT uq_despesas_movimentacao UNIQUE (id_movimentacao_financeira),
    CONSTRAINT fk_despesas_movimentacao FOREIGN KEY (id_movimentacao_financeira)
        REFERENCES movimentacoes_financeiras (id_movimentacao),
    CONSTRAINT fk_despesas_registrado_por FOREIGN KEY (registrado_por_usuario_id)
        REFERENCES usuarios (id_usuario)
);

CREATE INDEX ix_usuarios_criado_por ON usuarios (criado_por_usuario_id);
CREATE INDEX ix_tokens_redefinicao_usuario ON tokens_redefinicao_senha (id_usuario);
CREATE INDEX ix_pacientes_criado_por ON pacientes (criado_por_usuario_id);
CREATE INDEX ix_pacientes_atualizado_por ON pacientes (atualizado_por_usuario_id);
CREATE INDEX ix_historico_status_paciente ON historico_status_paciente (id_paciente);
CREATE INDEX ix_historico_status_usuario ON historico_status_paciente (alterado_por_usuario_id);
CREATE INDEX ix_voluntarios_criado_por ON voluntarios (criado_por_usuario_id);
CREATE INDEX ix_voluntarios_atualizado_por ON voluntarios (atualizado_por_usuario_id);
CREATE INDEX ix_categorias_equipamentos_criado_por ON categorias_equipamentos (criado_por_usuario_id);
CREATE INDEX ix_equipamentos_criado_por ON equipamentos (criado_por_usuario_id);
CREATE INDEX ix_equipamentos_categoria ON equipamentos (id_categoria);
CREATE INDEX ix_equipamentos_doacao ON equipamentos (id_doacao);
CREATE INDEX ix_equipamentos_status ON equipamentos (status);
CREATE UNIQUE INDEX uq_emprestimos_equipamento_aberto
    ON emprestimos_equipamentos (id_equipamento)
    WHERE data_devolucao IS NULL;
CREATE INDEX ix_emprestimos_paciente ON emprestimos_equipamentos (id_paciente);
CREATE INDEX ix_emprestimos_registrado_por ON emprestimos_equipamentos (registrado_por_usuario_id);
CREATE INDEX ix_doacoes_registrado_por ON doacoes (registrado_por_usuario_id);
CREATE INDEX ix_doacao_voluntarios_voluntario ON doacao_voluntarios (id_voluntario);
CREATE INDEX ix_movimentacoes_registrado_por ON movimentacoes_financeiras (registrado_por_usuario_id);
CREATE INDEX ix_despesas_registrado_por ON despesas (registrado_por_usuario_id);

CREATE VIEW vw_resumo_equipamentos_por_categoria AS
SELECT
    c.id_categoria,
    c.nome AS categoria,
    COUNT(e.id_equipamento) AS quantidade_total,
    COUNT(e.id_equipamento) FILTER (WHERE e.status = 'ATIVO') AS quantidade_ativa,
    COUNT(e.id_equipamento) FILTER (WHERE e.status = 'INATIVO') AS quantidade_inativa,
    COUNT(e.id_equipamento) FILTER (WHERE e.status = 'EMPRESTADO') AS quantidade_emprestada
FROM categorias_equipamentos c
LEFT JOIN equipamentos e ON e.id_categoria = c.id_categoria
GROUP BY c.id_categoria, c.nome;

-- Regras que exigem consulta a outras linhas/tabelas, como sincronizar o status
-- do equipamento com empréstimo e devolução, criar as unidades recebidas por
-- doação, conferir se a movimentação vinculada a uma despesa é do tipo SAIDA e
-- garantir que toda doação MONETARIA possua exatamente uma movimentação de ENTRADA,
-- devem ser implementadas em transações da aplicação ou em funções/triggers PostgreSQL.
