-- Permite criar contas sem senha temporaria. A senha definitiva somente passa
-- a existir depois que o usuario consome um token de ativacao valido.
ALTER TABLE usuarios
    ALTER COLUMN senha_hash DROP NOT NULL;

ALTER TABLE usuarios
    ADD CONSTRAINT ck_usuarios_credencial CHECK (
        (
            primeiro_acesso_pendente = TRUE
            AND senha_hash IS NULL
            AND senha_definitiva_em IS NULL
        )
        OR (
            primeiro_acesso_pendente = FALSE
            AND senha_hash IS NOT NULL
            AND senha_definitiva_em IS NOT NULL
        )
    );

-- A tabela passa a atender ativacao e futura redefinicao de senha sem
-- duplicar a infraestrutura de tokens.
ALTER TABLE tokens_redefinicao_senha
    RENAME TO tokens_credencial;

ALTER TABLE tokens_credencial
    RENAME CONSTRAINT pk_tokens_redefinicao_senha TO pk_tokens_credencial;

ALTER TABLE tokens_credencial
    RENAME CONSTRAINT uq_tokens_redefinicao_senha_hash TO uq_tokens_credencial_hash;

ALTER TABLE tokens_credencial
    RENAME CONSTRAINT fk_tokens_redefinicao_usuario TO fk_tokens_credencial_usuario;

ALTER TABLE tokens_credencial
    RENAME CONSTRAINT ck_tokens_redefinicao_hash TO ck_tokens_credencial_hash;

ALTER TABLE tokens_credencial
    RENAME CONSTRAINT ck_tokens_redefinicao_expiracao TO ck_tokens_credencial_expiracao;

ALTER TABLE tokens_credencial
    RENAME CONSTRAINT ck_tokens_redefinicao_utilizacao TO ck_tokens_credencial_utilizacao;

ALTER TABLE tokens_credencial
    ADD COLUMN finalidade VARCHAR(30) NOT NULL DEFAULT 'REDEFINICAO_SENHA';

ALTER TABLE tokens_credencial
    ALTER COLUMN finalidade DROP DEFAULT;

ALTER TABLE tokens_credencial
    ADD CONSTRAINT ck_tokens_credencial_finalidade CHECK (
        finalidade IN ('ATIVACAO', 'REDEFINICAO_SENHA')
    );

CREATE UNIQUE INDEX uq_tokens_credencial_usuario_finalidade_ativo
    ON tokens_credencial (id_usuario, finalidade)
    WHERE utilizado_em IS NULL;

CREATE TABLE historico_administracao_usuarios (
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    realizado_por_usuario_id BIGINT,
    tipo_evento VARCHAR(40) NOT NULL,
    perfil_anterior VARCHAR(20),
    perfil_novo VARCHAR(20),
    status_anterior VARCHAR(10),
    status_novo VARCHAR(10),
    justificativa VARCHAR(500),
    ocorrido_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_historico_administracao_usuarios PRIMARY KEY (id_evento),
    CONSTRAINT fk_historico_administracao_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_historico_administracao_responsavel FOREIGN KEY (realizado_por_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_historico_administracao_tipo CHECK (
        tipo_evento IN (
            'CRIACAO',
            'ATIVACAO',
            'REEMISSAO_ATIVACAO',
            'PROMOCAO_ADMINISTRADOR',
            'REBAIXAMENTO_USUARIO',
            'DESATIVACAO',
            'REATIVACAO'
        )
    ),
    CONSTRAINT ck_historico_administracao_perfil_anterior CHECK (
        perfil_anterior IS NULL OR perfil_anterior IN ('ADMINISTRADOR', 'USUARIO')
    ),
    CONSTRAINT ck_historico_administracao_perfil_novo CHECK (
        perfil_novo IS NULL OR perfil_novo IN ('ADMINISTRADOR', 'USUARIO')
    ),
    CONSTRAINT ck_historico_administracao_status_anterior CHECK (
        status_anterior IS NULL OR status_anterior IN ('ATIVO', 'INATIVO')
    ),
    CONSTRAINT ck_historico_administracao_status_novo CHECK (
        status_novo IS NULL OR status_novo IN ('ATIVO', 'INATIVO')
    )
);

CREATE INDEX ix_historico_administracao_usuario
    ON historico_administracao_usuarios (id_usuario, ocorrido_em DESC);

CREATE INDEX ix_historico_administracao_responsavel
    ON historico_administracao_usuarios (realizado_por_usuario_id);
