CREATE TABLE historico_exportacoes (
    id_exportacao BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_relatorio VARCHAR(40) NOT NULL,
    formato VARCHAR(10) NOT NULL,
    filtros VARCHAR(500),
    quantidade_registros INTEGER NOT NULL,
    exportado_por_usuario_id BIGINT NOT NULL,
    exportado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_historico_exportacoes PRIMARY KEY (id_exportacao),
    CONSTRAINT fk_historico_exportacoes_usuario FOREIGN KEY (exportado_por_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_historico_exportacoes_tipo CHECK (
        tipo_relatorio IN ('PACIENTES', 'VOLUNTARIOS', 'EMPRESTIMOS', 'DOACOES', 'MOVIMENTACOES_FINANCEIRAS')
    ),
    CONSTRAINT ck_historico_exportacoes_formato CHECK (formato IN ('PDF', 'XLSX')),
    CONSTRAINT ck_historico_exportacoes_quantidade CHECK (quantidade_registros >= 0)
);

CREATE INDEX ix_historico_exportacoes_usuario
    ON historico_exportacoes (exportado_por_usuario_id);

CREATE INDEX ix_historico_exportacoes_data
    ON historico_exportacoes (exportado_em DESC);
