CREATE TABLE historico_backups (
    id_backup BIGINT GENERATED BY DEFAULT AS IDENTITY,
    operacao VARCHAR(20) NOT NULL,
    resultado VARCHAR(20) NOT NULL,
    origem VARCHAR(30) NOT NULL,
    versao_backup VARCHAR(50),
    checksum VARCHAR(64),
    codigo_falha VARCHAR(60),
    responsavel_usuario_id BIGINT,
    realizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_historico_backups PRIMARY KEY (id_backup),
    CONSTRAINT fk_historico_backups_usuario FOREIGN KEY (responsavel_usuario_id)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_historico_backups_operacao CHECK (operacao IN ('EXPORTACAO', 'RESTAURACAO')),
    CONSTRAINT ck_historico_backups_resultado CHECK (resultado IN ('SUCESSO', 'FALHA')),
    CONSTRAINT ck_historico_backups_origem CHECK (
        origem IN ('PAINEL_ADMINISTRATIVO', 'RECUPERACAO_LOCAL')
    ),
    CONSTRAINT ck_historico_backups_checksum CHECK (
        checksum IS NULL OR checksum ~ '^[0-9A-Fa-f]{64}$'
    )
);

CREATE INDEX ix_historico_backups_usuario
    ON historico_backups (responsavel_usuario_id);

CREATE INDEX ix_historico_backups_data
    ON historico_backups (realizado_em DESC);
