package com.aclg.apecan.usuario.entity;

public enum TipoEventoAdministracaoUsuario {

	CRIACAO, ATIVACAO, REEMISSAO_ATIVACAO, PROMOCAO_ADMINISTRADOR, REBAIXAMENTO_USUARIO, DESATIVACAO, REATIVACAO,
	REDEFINICAO_SENHA, ALTERACAO_SENHA, CONVERSAO_PERFIL_ADM_DEV, ALTERACAO_PERFIL

}
